export const NOTIFICATION_TYPES = ['ASSET', 'MAINTENANCE', 'SCHEDULE', 'TICKET', 'ASSIGNMENT', 'MOVEMENT', 'REMINDER', 'SYSTEM'] as const;
export const NOTIFICATION_PRIORITIES = ['INFO', 'WARNING', 'CRITICAL', 'SUCCESS'] as const;
