import { pgTable, uuid, varchar, text, timestamp, date, numeric, integer, boolean, index } from 'drizzle-orm/pg-core';
import { assetCategories, assetSubcategories, brands, vendors, sites, buildings, floors, rooms, departments } from './master-data';
import { users } from './auth';

export const assets = pgTable('assets', {
  id: uuid('id').defaultRandom().primaryKey(),
  assetCode: varchar('asset_code', { length: 50 }).unique().notNull(),
  assetName: varchar('asset_name', { length: 200 }).notNull(),
  categoryId: uuid('category_id').references(() => assetCategories.id),
  subcategoryId: uuid('subcategory_id').references(() => assetSubcategories.id),
  brandId: uuid('brand_id').references(() => brands.id),
  model: varchar('model', { length: 150 }),
  serialNumber: varchar('serial_number', { length: 150 }),
  manufacturer: varchar('manufacturer', { length: 150 }),
  specification: text('specification'),
  purchaseDate: date('purchase_date'),
  purchasePrice: numeric('purchase_price', { precision: 15, scale: 2 }),
  vendorId: uuid('vendor_id').references(() => vendors.id),
  invoiceNumber: varchar('invoice_number', { length: 100 }),
  warrantyStart: date('warranty_start'),
  warrantyEnd: date('warranty_end'),
  siteId: uuid('site_id').references(() => sites.id),
  buildingId: uuid('building_id').references(() => buildings.id),
  floorId: uuid('floor_id').references(() => floors.id),
  roomId: uuid('room_id').references(() => rooms.id),
  departmentId: uuid('department_id').references(() => departments.id),
  currentPicId: uuid('current_pic_id').references(() => users.id),
  status: varchar('status', { length: 50 }).notNull().default('AVAILABLE'),
  condition: varchar('condition', { length: 50 }).notNull().default('GOOD'),
  healthScore: integer('health_score'),
  healthScoreUpdatedAt: timestamp('health_score_updated_at', { withTimezone: true }),
  repeatedFailure: boolean('repeated_failure').default(false).notNull(),
  qrCode: text('qr_code'),
  photoUrl: text('photo_url'),
  notes: text('notes'),
  createdBy: uuid('created_by').references(() => users.id),
  createdAt: timestamp('created_at', { withTimezone: true }).defaultNow().notNull(),
  updatedAt: timestamp('updated_at', { withTimezone: true }).defaultNow().notNull(),
  deletedAt: timestamp('deleted_at', { withTimezone: true }),
}, (table) => ({
  conditionIdx: index('assets_condition_idx').on(table.condition),
  healthScoreIdx: index('assets_health_score_idx').on(table.healthScore),
}));

export const assetConditionHistory = pgTable('asset_condition_history', {
  id: uuid('id').defaultRandom().primaryKey(),
  assetId: uuid('asset_id').notNull().references(() => assets.id),
  previousCondition: varchar('previous_condition', { length: 50 }).notNull(),
  newCondition: varchar('new_condition', { length: 50 }).notNull(),
  reason: text('reason'),
  notes: text('notes'),
  changedBy: uuid('changed_by').references(() => users.id),
  createdAt: timestamp('created_at', { withTimezone: true }).defaultNow().notNull(),
  inspectionScore: integer('inspection_score'),
  attachmentUrl: text('attachment_url'),
});

export const assetAssignments = pgTable('asset_assignments', {
  id: uuid('id').defaultRandom().primaryKey(),
  assetId: uuid('asset_id').notNull().references(() => assets.id),
  userId: uuid('user_id').references(() => users.id),
  departmentId: uuid('department_id').references(() => departments.id),
  assignedDate: date('assigned_date').notNull(),
  returnedDate: date('returned_date'),
  assignedBy: uuid('assigned_by').references(() => users.id),
  notes: text('notes'),
  status: varchar('status', { length: 50 }).notNull().default('ACTIVE'),
  createdAt: timestamp('created_at', { withTimezone: true }).defaultNow().notNull(),
  updatedAt: timestamp('updated_at', { withTimezone: true }).defaultNow().notNull(),
});

export const assetMovements = pgTable('asset_movements', {
  id: uuid('id').defaultRandom().primaryKey(),
  movementCode: varchar('movement_code', { length: 50 }),
  assetId: uuid('asset_id').notNull().references(() => assets.id),
  fromSiteId: uuid('from_site_id').references(() => sites.id),
  fromBuildingId: uuid('from_building_id').references(() => buildings.id),
  fromFloorId: uuid('from_floor_id').references(() => floors.id),
  fromRoomId: uuid('from_room_id').references(() => rooms.id),
  fromDepartmentId: uuid('from_department_id').references(() => departments.id),
  fromPicId: uuid('from_pic_id').references(() => users.id),
  toSiteId: uuid('to_site_id').references(() => sites.id),
  toBuildingId: uuid('to_building_id').references(() => buildings.id),
  toFloorId: uuid('to_floor_id').references(() => floors.id),
  toRoomId: uuid('to_room_id').references(() => rooms.id),
  toDepartmentId: uuid('to_department_id').references(() => departments.id),
  toPicId: uuid('to_pic_id').references(() => users.id),
  movementDate: date('movement_date').notNull(),
  reason: text('reason'),
  notes: text('notes'),
  movedBy: uuid('moved_by').references(() => users.id),
  approvedBy: uuid('approved_by').references(() => users.id),
  createdAt: timestamp('created_at', { withTimezone: true }).defaultNow().notNull(),
});

export const assetDocuments = pgTable('asset_documents', {
  id: uuid('id').defaultRandom().primaryKey(),
  assetId: uuid('asset_id').notNull().references(() => assets.id),
  documentType: varchar('document_type', { length: 50 }).notNull(),
  fileName: varchar('file_name', { length: 255 }).notNull(),
  fileUrl: text('file_url').notNull(),
  description: text('description'),
  uploadedBy: uuid('uploaded_by').references(() => users.id),
  createdAt: timestamp('created_at', { withTimezone: true }).defaultNow().notNull(),
});
